spring.application.name=campus-gigs

spring.datasource.url=jdbc:postgresql://localhost:5432/campusgigs
spring.datasource.username=campusgigs
spring.datasource.password=campusgigs
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080

api.security.token.secret=${JWT_SECRET:campusgigs-super-secret-key-para-desenvolvimento-com-mais-de-32-caracteres}
api.security.token.expiration=7200000
